# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/tmp_n/WebServer/webserver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/tmp_n/WebServer/webserver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/tmp_n/WebServer/webserver/CMakeFiles /root/tmp_n/WebServer/webserver/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/tmp_n/WebServer/webserver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named webserver

# Build rule for target.
webserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 webserver
.PHONY : webserver

# fast build rule for target.
webserver/fast:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/build
.PHONY : webserver/fast

CGImysql/sql_connection_pool.o: CGImysql/sql_connection_pool.cpp.o

.PHONY : CGImysql/sql_connection_pool.o

# target to build an object file
CGImysql/sql_connection_pool.cpp.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/CGImysql/sql_connection_pool.cpp.o
.PHONY : CGImysql/sql_connection_pool.cpp.o

CGImysql/sql_connection_pool.i: CGImysql/sql_connection_pool.cpp.i

.PHONY : CGImysql/sql_connection_pool.i

# target to preprocess a source file
CGImysql/sql_connection_pool.cpp.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/CGImysql/sql_connection_pool.cpp.i
.PHONY : CGImysql/sql_connection_pool.cpp.i

CGImysql/sql_connection_pool.s: CGImysql/sql_connection_pool.cpp.s

.PHONY : CGImysql/sql_connection_pool.s

# target to generate assembly for a file
CGImysql/sql_connection_pool.cpp.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/CGImysql/sql_connection_pool.cpp.s
.PHONY : CGImysql/sql_connection_pool.cpp.s

config.o: config.cpp.o

.PHONY : config.o

# target to build an object file
config.cpp.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/config.cpp.o
.PHONY : config.cpp.o

config.i: config.cpp.i

.PHONY : config.i

# target to preprocess a source file
config.cpp.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/config.cpp.i
.PHONY : config.cpp.i

config.s: config.cpp.s

.PHONY : config.s

# target to generate assembly for a file
config.cpp.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/config.cpp.s
.PHONY : config.cpp.s

http/http_conn.o: http/http_conn.cpp.o

.PHONY : http/http_conn.o

# target to build an object file
http/http_conn.cpp.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/http/http_conn.cpp.o
.PHONY : http/http_conn.cpp.o

http/http_conn.i: http/http_conn.cpp.i

.PHONY : http/http_conn.i

# target to preprocess a source file
http/http_conn.cpp.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/http/http_conn.cpp.i
.PHONY : http/http_conn.cpp.i

http/http_conn.s: http/http_conn.cpp.s

.PHONY : http/http_conn.s

# target to generate assembly for a file
http/http_conn.cpp.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/http/http_conn.cpp.s
.PHONY : http/http_conn.cpp.s

log/log.o: log/log.cpp.o

.PHONY : log/log.o

# target to build an object file
log/log.cpp.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/log/log.cpp.o
.PHONY : log/log.cpp.o

log/log.i: log/log.cpp.i

.PHONY : log/log.i

# target to preprocess a source file
log/log.cpp.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/log/log.cpp.i
.PHONY : log/log.cpp.i

log/log.s: log/log.cpp.s

.PHONY : log/log.s

# target to generate assembly for a file
log/log.cpp.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/log/log.cpp.s
.PHONY : log/log.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/main.cpp.s
.PHONY : main.cpp.s

timer/lst_timer.o: timer/lst_timer.cpp.o

.PHONY : timer/lst_timer.o

# target to build an object file
timer/lst_timer.cpp.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/timer/lst_timer.cpp.o
.PHONY : timer/lst_timer.cpp.o

timer/lst_timer.i: timer/lst_timer.cpp.i

.PHONY : timer/lst_timer.i

# target to preprocess a source file
timer/lst_timer.cpp.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/timer/lst_timer.cpp.i
.PHONY : timer/lst_timer.cpp.i

timer/lst_timer.s: timer/lst_timer.cpp.s

.PHONY : timer/lst_timer.s

# target to generate assembly for a file
timer/lst_timer.cpp.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/timer/lst_timer.cpp.s
.PHONY : timer/lst_timer.cpp.s

webserver.o: webserver.cpp.o

.PHONY : webserver.o

# target to build an object file
webserver.cpp.o:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver.cpp.o
.PHONY : webserver.cpp.o

webserver.i: webserver.cpp.i

.PHONY : webserver.i

# target to preprocess a source file
webserver.cpp.i:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver.cpp.i
.PHONY : webserver.cpp.i

webserver.s: webserver.cpp.s

.PHONY : webserver.s

# target to generate assembly for a file
webserver.cpp.s:
	$(MAKE) -f CMakeFiles/webserver.dir/build.make CMakeFiles/webserver.dir/webserver.cpp.s
.PHONY : webserver.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... webserver"
	@echo "... CGImysql/sql_connection_pool.o"
	@echo "... CGImysql/sql_connection_pool.i"
	@echo "... CGImysql/sql_connection_pool.s"
	@echo "... config.o"
	@echo "... config.i"
	@echo "... config.s"
	@echo "... http/http_conn.o"
	@echo "... http/http_conn.i"
	@echo "... http/http_conn.s"
	@echo "... log/log.o"
	@echo "... log/log.i"
	@echo "... log/log.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... timer/lst_timer.o"
	@echo "... timer/lst_timer.i"
	@echo "... timer/lst_timer.s"
	@echo "... webserver.o"
	@echo "... webserver.i"
	@echo "... webserver.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

